// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd8e2IH34dJiGjVlXAod9cfg6fn0uOcO8',
    appId: '1:779598436080:web:e7de4ebaf1437f11ec5435',
    messagingSenderId: '779598436080',
    projectId: 'smart-traffic-28a15',
    authDomain: 'smart-traffic-28a15.firebaseapp.com',
    databaseURL: 'https://smart-traffic-28a15-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-28a15.firebasestorage.app',
    measurementId: 'G-Q2PXQYDRK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOoUUFzWeLAvEsTRYFxMFEDM3Uzuyp90',
    appId: '1:779598436080:android:49897f3cbda4f243ec5435',
    messagingSenderId: '779598436080',
    projectId: 'smart-traffic-28a15',
    databaseURL: 'https://smart-traffic-28a15-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-28a15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7YNwCOXBUTz_LPELJC7F0Ht1MriZ46qY',
    appId: '1:779598436080:ios:351cf8240829c692ec5435',
    messagingSenderId: '779598436080',
    projectId: 'smart-traffic-28a15',
    databaseURL: 'https://smart-traffic-28a15-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-28a15.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7YNwCOXBUTz_LPELJC7F0Ht1MriZ46qY',
    appId: '1:779598436080:ios:351cf8240829c692ec5435',
    messagingSenderId: '779598436080',
    projectId: 'smart-traffic-28a15',
    databaseURL: 'https://smart-traffic-28a15-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-28a15.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd8e2IH34dJiGjVlXAod9cfg6fn0uOcO8',
    appId: '1:779598436080:web:52a00bd4c5d384caec5435',
    messagingSenderId: '779598436080',
    projectId: 'smart-traffic-28a15',
    authDomain: 'smart-traffic-28a15.firebaseapp.com',
    databaseURL: 'https://smart-traffic-28a15-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-28a15.firebasestorage.app',
    measurementId: 'G-VSEZ8B3SNM',
  );
}
